"""Closed vocabularies for hypothetical simulation and backtesting."""

from __future__ import annotations

from enum import StrEnum


class RunType(StrEnum):
    SHADOW = "SHADOW"
    BACKTEST = "BACKTEST"


class ExperimentStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATING = "VALIDATING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_GAPS = "COMPLETED_WITH_GAPS"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SimulationRunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    INCOMPLETE = "INCOMPLETE"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class BacktestRunStatus(StrEnum):
    PENDING = "PENDING"
    VALIDATING = "VALIDATING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_GAPS = "COMPLETED_WITH_GAPS"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SimulatedPositionState(StrEnum):
    """State of ONE hypothetical simulated position (never a real one)."""

    PENDING_DELAY = "PENDING_DELAY"
    MODELLED_ENTRY = "MODELLED_ENTRY"
    OPEN_SIMULATION = "OPEN_SIMULATION"
    PARTIAL_REDUCTION_MODELLED = "PARTIAL_REDUCTION_MODELLED"
    CLOSED_SIMULATION = "CLOSED_SIMULATION"
    UNMODELED_EXIT = "UNMODELED_EXIT"
    INCOMPLETE = "INCOMPLETE"
    REJECTED = "REJECTED"


class DelayModel(StrEnum):
    FIXED_SECONDS = "FIXED_SECONDS"
    UNIFORM_RANGE_SECONDS = "UNIFORM_RANGE_SECONDS"
    LOGNORMAL_DELAY = "LOGNORMAL_DELAY"
    EVENT_TIMESTAMP_ONLY = "EVENT_TIMESTAMP_ONLY"


class SimulationExitReason(StrEnum):
    """Exit reasons mirror phase-10 lifecycle events - never new rules."""

    TARGET_1_OBSERVED = "TARGET_1_OBSERVED"
    TARGET_2_OBSERVED = "TARGET_2_OBSERVED"
    TECHNICAL_EXIT_CONDITION = "TECHNICAL_EXIT_CONDITION"
    INVALIDATION_CONDITION = "INVALIDATION_CONDITION"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"
    DATA_INVALID = "DATA_INVALID"
    SESSION_POLICY_END = "SESSION_POLICY_END"
    LIFECYCLE_TERMINAL = "LIFECYCLE_TERMINAL"


class SimulationLegKind(StrEnum):
    """Which modelled leg an execution record describes."""

    MODELLED_ENTRY = "MODELLED_ENTRY"
    MODELLED_PARTIAL_REDUCTION = "MODELLED_PARTIAL_REDUCTION"
    MODELLED_EXIT = "MODELLED_EXIT"


class SimulationRejectionCode(StrEnum):
    LIFECYCLE_NOT_ELIGIBLE = "LIFECYCLE_NOT_ELIGIBLE"
    PLAN_AUDIT_MISSING = "PLAN_AUDIT_MISSING"
    CANDIDATE_AUDIT_MISSING = "CANDIDATE_AUDIT_MISSING"
    SIMULATION_DISABLED = "SIMULATION_DISABLED"
    BOT_PAUSED = "BOT_PAUSED"
    DUPLICATE_SIMULATION = "DUPLICATE_SIMULATION"
    ENTRY_DELAY_DATA_UNAVAILABLE = "ENTRY_DELAY_DATA_UNAVAILABLE"
    ENTRY_BOOK_STALE = "ENTRY_BOOK_STALE"
    ENTRY_BOOK_INSUFFICIENT_DEPTH = "ENTRY_BOOK_INSUFFICIENT_DEPTH"
    ENTRY_SLIPPAGE_EXCESSIVE = "ENTRY_SLIPPAGE_EXCESSIVE"
    EXIT_BOOK_STALE = "EXIT_BOOK_STALE"
    EXIT_BOOK_INSUFFICIENT_DEPTH = "EXIT_BOOK_INSUFFICIENT_DEPTH"
    EXIT_UNMODELED = "EXIT_UNMODELED"
    FUNDING_UNAVAILABLE = "FUNDING_UNAVAILABLE"
    FEE_SCHEDULE_UNAVAILABLE = "FEE_SCHEDULE_UNAVAILABLE"
    COST_MODEL_UNAVAILABLE = "COST_MODEL_UNAVAILABLE"
    DATA_GAP = "DATA_GAP"
    SESSION_NOT_ALLOWED = "SESSION_NOT_ALLOWED"
    MANIFEST_INVALID = "MANIFEST_INVALID"
    BACKTEST_DATA_INCOMPLETE = "BACKTEST_DATA_INCOMPLETE"
    LOOKAHEAD_GUARD_TRIGGERED = "LOOKAHEAD_GUARD_TRIGGERED"
    INSUFFICIENT_SAMPLE = "INSUFFICIENT_SAMPLE"
    CONFIGURATION_INVALID = "CONFIGURATION_INVALID"
    EXPERIMENT_CANCELLED = "EXPERIMENT_CANCELLED"
    SIMULATION_ERROR = "SIMULATION_ERROR"


class SimulationEventType(StrEnum):
    """Audit trail of one hypothetical simulation."""

    SIMULATION_CREATED = "SIMULATION_CREATED"
    DELAY_SCHEDULED = "DELAY_SCHEDULED"
    ENTRY_MODELLED = "ENTRY_MODELLED"
    PARTIAL_REDUCTION_MODELLED = "PARTIAL_REDUCTION_MODELLED"
    EXIT_MODELLED = "EXIT_MODELLED"
    EXIT_UNMODELED = "EXIT_UNMODELED"
    FUNDING_MODELLED = "FUNDING_MODELLED"
    SIMULATION_COMPLETED = "SIMULATION_COMPLETED"
    SIMULATION_INCOMPLETE = "SIMULATION_INCOMPLETE"
    SIMULATION_REJECTED = "SIMULATION_REJECTED"


class DataCompleteness(StrEnum):
    """How complete the public inputs of one simulation were."""

    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    INSUFFICIENT = "INSUFFICIENT"


class ReplayEventCategory(StrEnum):
    """Versioned replay ordering categories (ascending priority order)."""

    SESSION_CALENDAR = "SESSION_CALENDAR"
    INSTRUMENT_STATUS = "INSTRUMENT_STATUS"
    DATA_QUALITY_BOOK = "DATA_QUALITY_BOOK"
    TICKER_BBO_TRADES = "TICKER_BBO_TRADES"
    CLOSED_CANDLE = "CLOSED_CANDLE"
    STRATEGY_EVALUATION = "STRATEGY_EVALUATION"
    RISK_PLAN_EVALUATION = "RISK_PLAN_EVALUATION"
    LIFECYCLE_MONITORING = "LIFECYCLE_MONITORING"
    SIMULATION_EXECUTION = "SIMULATION_EXECUTION"


class WalkForwardMode(StrEnum):
    ROLLING = "ROLLING"
    EXPANDING = "EXPANDING"


class WalkForwardWindow(StrEnum):
    TRAIN = "TRAIN"
    VALIDATION = "VALIDATION"
    TEST = "TEST"


class MetricSampleStatus(StrEnum):
    """Whether a metric set rests on enough complete simulations."""

    SUFFICIENT = "SUFFICIENT"
    INSUFFICIENT_SAMPLE = "INSUFFICIENT_SAMPLE"


class SimulationSubsystemState(StrEnum):
    DISABLED = "DISABLED"
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
