"""Selection enums and structured reason codes."""

from __future__ import annotations

from enum import StrEnum


class InstrumentEligibilityStatus(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    INELIGIBLE = "INELIGIBLE"
    DISABLED_BY_POLICY = "DISABLED_BY_POLICY"
    DISABLED_BY_CONFIG = "DISABLED_BY_CONFIG"
    MARKET_INACTIVE = "MARKET_INACTIVE"
    ASSET_CLASS_UNSUPPORTED = "ASSET_CLASS_UNSUPPORTED"
    SESSION_CLOSED = "SESSION_CLOSED"
    HOLIDAY_CLOSED = "HOLIDAY_CLOSED"
    WEEKEND_CLOSED = "WEEKEND_CLOSED"
    EARLY_CLOSE_ENDED = "EARLY_CLOSE_ENDED"
    CALENDAR_UNAVAILABLE = "CALENDAR_UNAVAILABLE"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"
    DATA_STALE = "DATA_STALE"
    DATA_INVALID = "DATA_INVALID"
    ORDERBOOK_RESYNCING = "ORDERBOOK_RESYNCING"
    LOW_VOLUME = "LOW_VOLUME"
    SPREAD_TOO_WIDE = "SPREAD_TOO_WIDE"
    INSUFFICIENT_DEPTH = "INSUFFICIENT_DEPTH"
    PRICE_INVALID = "PRICE_INVALID"
    VOLUME_UNAVAILABLE = "VOLUME_UNAVAILABLE"
    INSTRUMENT_NOT_CONFIGURED = "INSTRUMENT_NOT_CONFIGURED"
    INSTRUMENT_DELISTED = "INSTRUMENT_DELISTED"
    INSTRUMENT_UNKNOWN = "INSTRUMENT_UNKNOWN"


class MarketSelectionState(StrEnum):
    DISCOVERED = "DISCOVERED"
    CLASSIFIED = "CLASSIFIED"
    PENDING_QUALITY = "PENDING_QUALITY"
    WATCHLIST_ELIGIBLE = "WATCHLIST_ELIGIBLE"
    WATCHLIST_ACTIVE = "WATCHLIST_ACTIVE"
    WATCHLIST_PAUSED = "WATCHLIST_PAUSED"
    REJECTED = "REJECTED"
    REMOVED = "REMOVED"


class WatchlistEventType(StrEnum):
    WATCHLIST_ADDED = "WATCHLIST_ADDED"
    WATCHLIST_PAUSED = "WATCHLIST_PAUSED"
    WATCHLIST_REMOVED = "WATCHLIST_REMOVED"
    WATCHLIST_RESTORED = "WATCHLIST_RESTORED"
    SELECTION_REJECTED = "SELECTION_REJECTED"


class SelectionSubsystemState(StrEnum):
    DISABLED = "DISABLED"
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"


#: additional structured reason codes (besides eligibility-status codes).
#: Reasons never imply a trade direction.
REASON_DATA_DEGRADED = "DATA_DEGRADED"
REASON_ORDERBOOK_STALE = "ORDERBOOK_STALE"
REASON_BBO_UNAVAILABLE = "BBO_UNAVAILABLE"
REASON_SPREAD_UNAVAILABLE = "SPREAD_UNAVAILABLE"
REASON_PRICE_CONSISTENCY_UNAVAILABLE = "PRICE_CONSISTENCY_UNAVAILABLE"
REASON_DEPTH_ASYMMETRY = "DEPTH_ASYMMETRY"
REASON_QUALITY_BELOW_MINIMUM = "QUALITY_SCORE_BELOW_MINIMUM"
REASON_THIN_LIQUIDITY_WINDOW = "THIN_LIQUIDITY_WINDOW"
REASON_WATCHLIST_FULL = "WATCHLIST_FULL"
REASON_NOT_IN_ALLOWLIST = "NOT_IN_ALLOWLIST"
