"""Risk engine enums.

Directions and prices in this package are hypothetical research references -
never orders, never recommendations.
"""

from __future__ import annotations

from enum import StrEnum


class PlanStatus(StrEnum):
    CANDIDATE_RECEIVED = "CANDIDATE_RECEIVED"
    EVALUATING = "EVALUATING"
    ELIGIBLE = "ELIGIBLE"
    INELIGIBLE = "INELIGIBLE"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"
    DATA_INVALID = "DATA_INVALID"
    PAUSED = "PAUSED"


class PlanRejectionCode(StrEnum):
    CANDIDATE_NOT_CONFIRMED = "CANDIDATE_NOT_CONFIRMED"
    CANDIDATE_EXPIRED = "CANDIDATE_EXPIRED"
    CANDIDATE_SUPERSEDED = "CANDIDATE_SUPERSEDED"
    BOT_PAUSED = "BOT_PAUSED"
    SESSION_NOT_ALLOWED = "SESSION_NOT_ALLOWED"
    INSTRUMENT_RISK_DATA_MISSING = "INSTRUMENT_RISK_DATA_MISSING"
    INSTRUMENT_INACTIVE = "INSTRUMENT_INACTIVE"
    DATA_QUALITY_INSUFFICIENT = "DATA_QUALITY_INSUFFICIENT"
    ORDERBOOK_NOT_FRESH = "ORDERBOOK_NOT_FRESH"
    ORDERBOOK_DEPTH_INSUFFICIENT = "ORDERBOOK_DEPTH_INSUFFICIENT"
    REFERENCE_ENTRY_UNAVAILABLE = "REFERENCE_ENTRY_UNAVAILABLE"
    INVALIDATION_UNAVAILABLE = "INVALIDATION_UNAVAILABLE"
    INVALIDATION_WRONG_SIDE = "INVALIDATION_WRONG_SIDE"
    INVALIDATION_TOO_CLOSE = "INVALIDATION_TOO_CLOSE"
    INVALIDATION_TOO_FAR = "INVALIDATION_TOO_FAR"
    REFERENCE_TARGET_UNAVAILABLE = "REFERENCE_TARGET_UNAVAILABLE"
    TARGET_WRONG_SIDE = "TARGET_WRONG_SIDE"
    MIN_NOTIONAL_VIOLATION = "MIN_NOTIONAL_VIOLATION"
    REFERENCE_QUANTITY_INVALID = "REFERENCE_QUANTITY_INVALID"
    MAX_LEVERAGE_UNAVAILABLE = "MAX_LEVERAGE_UNAVAILABLE"
    MARGIN_MODEL_UNAVAILABLE = "MARGIN_MODEL_UNAVAILABLE"
    MAINTENANCE_MARGIN_UNAVAILABLE = "MAINTENANCE_MARGIN_UNAVAILABLE"
    LIQUIDATION_BUFFER_INSUFFICIENT = "LIQUIDATION_BUFFER_INSUFFICIENT"
    FEE_SCHEDULE_UNAVAILABLE = "FEE_SCHEDULE_UNAVAILABLE"
    EXECUTION_ASSUMPTION_UNAVAILABLE = "EXECUTION_ASSUMPTION_UNAVAILABLE"
    SLIPPAGE_MODEL_UNAVAILABLE = "SLIPPAGE_MODEL_UNAVAILABLE"
    SLIPPAGE_EXCESSIVE = "SLIPPAGE_EXCESSIVE"
    FUNDING_MODEL_UNAVAILABLE = "FUNDING_MODEL_UNAVAILABLE"
    FUNDING_COST_EXCESSIVE = "FUNDING_COST_EXCESSIVE"
    EQUITY_OVERNIGHT_BLOCKED = "EQUITY_OVERNIGHT_BLOCKED"
    NET_TARGET_NON_POSITIVE = "NET_TARGET_NON_POSITIVE"
    NET_RR_BELOW_THRESHOLD = "NET_RR_BELOW_THRESHOLD"
    COST_TO_RISK_EXCESSIVE = "COST_TO_RISK_EXCESSIVE"
    ELIGIBILITY_SCORE_BELOW_THRESHOLD = "ELIGIBILITY_SCORE_BELOW_THRESHOLD"
    CONFIGURATION_INVALID = "CONFIGURATION_INVALID"
    PLAN_DUPLICATE = "PLAN_DUPLICATE"
    EVALUATION_ERROR = "EVALUATION_ERROR"


class InvalidationBasis(StrEnum):
    SWEPT_LEVEL = "SWEPT_LEVEL"
    RECLAIM_LEVEL = "RECLAIM_LEVEL"
    STRUCTURE_LEVEL = "STRUCTURE_LEVEL"
    RANGE_BOUNDARY = "RANGE_BOUNDARY"


class EntryBasis(StrEnum):
    RECLAIM_LEVEL = "RECLAIM_LEVEL"
    RETEST_ZONE = "RETEST_ZONE"
    BREAKOUT_CLOSE_ZONE = "BREAKOUT_CLOSE_ZONE"
    STRUCTURE_LEVEL_ZONE = "STRUCTURE_LEVEL_ZONE"


class TargetLevelType(StrEnum):
    LIQUIDITY_POOL = "LIQUIDITY_POOL"
    SWING_LEVEL = "SWING_LEVEL"
    RANGE_BOUNDARY = "RANGE_BOUNDARY"
    EQUAL_LEVEL_CLUSTER = "EQUAL_LEVEL_CLUSTER"


class MarginModelMode(StrEnum):
    UNAVAILABLE = "UNAVAILABLE"
    PUBLIC_RATES = "PUBLIC_RATES"  # rates from public instrument metadata
    APPROXIMATED = "APPROXIMATED"  # opt-in only, prominently flagged


class RiskSubsystemState(StrEnum):
    DISABLED = "DISABLED"
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"


class PlanEventType(StrEnum):
    CREATED = "CREATED"
    ELIGIBLE = "ELIGIBLE"
    INELIGIBLE = "INELIGIBLE"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"
    DATA_INVALID = "DATA_INVALID"
    PAUSED = "PAUSED"
