"""Strategy enums.  Directions are research/structure classifications only."""

from __future__ import annotations

from enum import StrEnum


class StrategyRegime(StrEnum):
    TREND_UP = "TREND_UP"
    TREND_DOWN = "TREND_DOWN"
    RANGE = "RANGE"
    BREAKOUT = "BREAKOUT"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LOW_LIQUIDITY = "LOW_LIQUIDITY"
    EVENT_RISK = "EVENT_RISK"
    NO_TRADE = "NO_TRADE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class StructureState(StrEnum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    NEUTRAL = "NEUTRAL"
    TRANSITIONAL = "TRANSITIONAL"
    INSUFFICIENT_STRUCTURE = "INSUFFICIENT_STRUCTURE"


class SwingType(StrEnum):
    HIGH = "HIGH"
    LOW = "LOW"


class StructureEventType(StrEnum):
    HIGHER_HIGH = "HIGHER_HIGH"
    HIGHER_LOW = "HIGHER_LOW"
    LOWER_HIGH = "LOWER_HIGH"
    LOWER_LOW = "LOWER_LOW"
    EQUAL_HIGH = "EQUAL_HIGH"
    EQUAL_LOW = "EQUAL_LOW"
    BREAK_OF_STRUCTURE = "BREAK_OF_STRUCTURE"
    CHANGE_OF_CHARACTER = "CHANGE_OF_CHARACTER"


class LiquidityLevelType(StrEnum):
    SWING_HIGH = "SWING_HIGH"
    SWING_LOW = "SWING_LOW"
    EQUAL_HIGHS = "EQUAL_HIGHS"
    EQUAL_LOWS = "EQUAL_LOWS"
    RANGE_HIGH = "RANGE_HIGH"
    RANGE_LOW = "RANGE_LOW"


class SweepDirection(StrEnum):
    ABOVE = "ABOVE"  # liquidity above (highs) was swept
    BELOW = "BELOW"  # liquidity below (lows) was swept


class RetestStatus(StrEnum):
    CONFIRMED = "CONFIRMED"
    FAILED = "FAILED"
    PENDING = "PENDING"
    NOT_PRESENT = "NOT_PRESENT"


class CandidateType(StrEnum):
    BULLISH_RECLAIM_CONTINUATION = "BULLISH_RECLAIM_CONTINUATION"
    BEARISH_REJECTION_CONTINUATION = "BEARISH_REJECTION_CONTINUATION"
    BULLISH_SWEEP_REVERSAL = "BULLISH_SWEEP_REVERSAL"
    BEARISH_SWEEP_REVERSAL = "BEARISH_SWEEP_REVERSAL"
    RANGE_BREAKOUT_UP = "RANGE_BREAKOUT_UP"
    RANGE_BREAKOUT_DOWN = "RANGE_BREAKOUT_DOWN"


class CandidateDirection(StrEnum):
    """Research/structure direction of a candidate - not a trade instruction."""

    BULLISH = "BULLISH"
    BEARISH = "BEARISH"


class CandidateState(StrEnum):
    DETECTED = "DETECTED"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"


class RejectionCode(StrEnum):
    NOT_ON_ACTIVE_WATCHLIST = "NOT_ON_ACTIVE_WATCHLIST"
    SESSION_NOT_ALLOWED = "SESSION_NOT_ALLOWED"
    BOT_PAUSED = "BOT_PAUSED"
    INSUFFICIENT_CANDLE_HISTORY = "INSUFFICIENT_CANDLE_HISTORY"
    CANDLE_GAP = "CANDLE_GAP"
    OPEN_CANDLE_ONLY = "OPEN_CANDLE_ONLY"
    DATA_QUALITY_NOT_SUFFICIENT = "DATA_QUALITY_NOT_SUFFICIENT"
    ORDERBOOK_NOT_FRESH = "ORDERBOOK_NOT_FRESH"
    REGIME_NO_TRADE = "REGIME_NO_TRADE"
    REGIME_HIGH_VOLATILITY = "REGIME_HIGH_VOLATILITY"
    REGIME_LOW_LIQUIDITY = "REGIME_LOW_LIQUIDITY"
    REGIME_INSUFFICIENT_DATA = "REGIME_INSUFFICIENT_DATA"
    HIGHER_TIMEFRAME_CONFLICT = "HIGHER_TIMEFRAME_CONFLICT"
    STRUCTURE_NOT_CONFIRMED = "STRUCTURE_NOT_CONFIRMED"
    NO_RELEVANT_LIQUIDITY_EVENT = "NO_RELEVANT_LIQUIDITY_EVENT"
    SWEEP_UNCONFIRMED = "SWEEP_UNCONFIRMED"
    RECLAIM_UNCONFIRMED = "RECLAIM_UNCONFIRMED"
    REJECTION_UNCONFIRMED = "REJECTION_UNCONFIRMED"
    RETEST_PENDING = "RETEST_PENDING"
    MOMENTUM_INSUFFICIENT = "MOMENTUM_INSUFFICIENT"
    VOLUME_INSUFFICIENT = "VOLUME_INSUFFICIENT"
    SETUP_SCORE_BELOW_THRESHOLD = "SETUP_SCORE_BELOW_THRESHOLD"
    CANDIDATE_DUPLICATE = "CANDIDATE_DUPLICATE"
    CANDIDATE_SUPERSEDED = "CANDIDATE_SUPERSEDED"
    EVALUATION_ERROR = "EVALUATION_ERROR"


class StrategySubsystemState(StrEnum):
    DISABLED = "DISABLED"
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
