"""Signal lifecycle enums.

States describe the TECHNICAL development of a research signal only - they
never imply that a user traded or holds a position.
"""

from __future__ import annotations

from enum import StrEnum


class SignalState(StrEnum):
    DRAFT = "DRAFT"
    PENDING_ADMISSION = "PENDING_ADMISSION"
    WATCHING_ENTRY = "WATCHING_ENTRY"
    ENTRY_CONFIRMED = "ENTRY_CONFIRMED"
    ACTIVE_RESEARCH = "ACTIVE_RESEARCH"
    TARGET_1_REACHED = "TARGET_1_REACHED"
    TARGET_2_REACHED = "TARGET_2_REACHED"
    TRAILING_RESEARCH = "TRAILING_RESEARCH"
    TECHNICAL_EXIT = "TECHNICAL_EXIT"
    INVALIDATED = "INVALIDATED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"
    PAUSED = "PAUSED"
    REJECTED = "REJECTED"
    DATA_INVALID = "DATA_INVALID"


class SignalRejectionCode(StrEnum):
    PLAN_NOT_ELIGIBLE = "PLAN_NOT_ELIGIBLE"
    PLAN_EXPIRED = "PLAN_EXPIRED"
    CANDIDATE_NOT_CONFIRMED = "CANDIDATE_NOT_CONFIRMED"
    CANDIDATE_EXPIRED = "CANDIDATE_EXPIRED"
    CANDIDATE_SUPERSEDED = "CANDIDATE_SUPERSEDED"
    WATCHLIST_NOT_ACTIVE = "WATCHLIST_NOT_ACTIVE"
    SESSION_NOT_ALLOWED = "SESSION_NOT_ALLOWED"
    MARKET_QUALITY_INSUFFICIENT = "MARKET_QUALITY_INSUFFICIENT"
    DATA_QUALITY_INSUFFICIENT = "DATA_QUALITY_INSUFFICIENT"
    ORDERBOOK_NOT_FRESH = "ORDERBOOK_NOT_FRESH"
    PLAN_SNAPSHOT_STALE = "PLAN_SNAPSHOT_STALE"
    CANDIDATE_SNAPSHOT_STALE = "CANDIDATE_SNAPSHOT_STALE"
    INSTRUMENT_SNAPSHOT_STALE = "INSTRUMENT_SNAPSHOT_STALE"
    BOT_PAUSED = "BOT_PAUSED"
    ACTIVE_SIGNAL_LIMIT_REACHED = "ACTIVE_SIGNAL_LIMIT_REACHED"
    SIGNAL_DUPLICATE = "SIGNAL_DUPLICATE"
    ADMISSION_CONFIGURATION_INVALID = "ADMISSION_CONFIGURATION_INVALID"
    ADMISSION_ERROR = "ADMISSION_ERROR"
    INVALID_TRANSITION = "INVALID_TRANSITION"
    STATE_VERSION_CONFLICT = "STATE_VERSION_CONFLICT"


class SignalEventType(StrEnum):
    """One event per persisted state transition (plus creation)."""

    CREATED = "CREATED"
    ADMITTED = "ADMITTED"
    WATCHING_ENTRY = "WATCHING_ENTRY"
    ENTRY_CONFIRMED = "ENTRY_CONFIRMED"
    ACTIVE_RESEARCH = "ACTIVE_RESEARCH"
    TARGET_1_REACHED = "TARGET_1_REACHED"
    TARGET_2_REACHED = "TARGET_2_REACHED"
    TRAILING_RESEARCH = "TRAILING_RESEARCH"
    TECHNICAL_EXIT = "TECHNICAL_EXIT"
    INVALIDATED = "INVALIDATED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"
    PAUSED = "PAUSED"
    REJECTED = "REJECTED"
    DATA_INVALID = "DATA_INVALID"


class SignalUpdateType(StrEnum):
    """Observation stream, separate from state transitions."""

    ADMITTED = "ADMITTED"
    WATCHING_ENTRY = "WATCHING_ENTRY"
    ENTRY_CONDITION_OBSERVED = "ENTRY_CONDITION_OBSERVED"
    ENTRY_CONFIRMED = "ENTRY_CONFIRMED"
    TARGET_1_OBSERVED = "TARGET_1_OBSERVED"
    TARGET_2_OBSERVED = "TARGET_2_OBSERVED"
    TECHNICAL_EXIT_CONDITION = "TECHNICAL_EXIT_CONDITION"
    INVALIDATION_CONDITION = "INVALIDATION_CONDITION"
    DATA_QUALITY_DEGRADED = "DATA_QUALITY_DEGRADED"
    SESSION_TRANSITION = "SESSION_TRANSITION"
    PLAN_CHANGED = "PLAN_CHANGED"
    CANDIDATE_CHANGED = "CANDIDATE_CHANGED"
    EXPIRY_WARNING = "EXPIRY_WARNING"
    SUPERSEDE_WARNING = "SUPERSEDE_WARNING"
    LIFECYCLE_ERROR = "LIFECYCLE_ERROR"


class EntryTriggerType(StrEnum):
    ZONE_TOUCH = "ZONE_TOUCH"
    ZONE_TOUCH_AND_5M_CLOSE_CONFIRM = "ZONE_TOUCH_AND_5M_CLOSE_CONFIRM"
    RECLAIM_LEVEL_CLOSE_CONFIRM = "RECLAIM_LEVEL_CLOSE_CONFIRM"
    RETEST_CONFIRM = "RETEST_CONFIRM"
    BREAKOUT_CLOSE_CONFIRM = "BREAKOUT_CLOSE_CONFIRM"


class InvalidationTriggerPolicy(StrEnum):
    MARK_PRICE_TOUCH = "MARK_PRICE_TOUCH"
    BBO_TOUCH = "BBO_TOUCH"
    FIVE_M_CLOSE_BEYOND_LEVEL = "FIVE_M_CLOSE_BEYOND_LEVEL"
    CONSERVATIVE_COMBINED = "CONSERVATIVE_COMBINED"


class TargetTriggerPolicy(StrEnum):
    MARK_PRICE_TOUCH = "MARK_PRICE_TOUCH"
    BBO_TOUCH = "BBO_TOUCH"
    FIVE_M_CLOSE_AT_OR_BEYOND_TARGET = "FIVE_M_CLOSE_AT_OR_BEYOND_TARGET"


class SessionEndPolicy(StrEnum):
    EXPIRE = "EXPIRE"
    PAUSE = "PAUSE"
    TECHNICAL_EXIT = "TECHNICAL_EXIT"


class PostEntryExpiryPolicy(StrEnum):
    EXPIRE = "EXPIRE"
    TECHNICAL_EXIT = "TECHNICAL_EXIT"


class SignalSubsystemState(StrEnum):
    DISABLED = "DISABLED"
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
